### ISSUE TITLE
2.13inch e-Paper HAT (C)

### ISSUE THREAD

**Issue by nopnop2002** [Bodmer/EPD_Libraries#2]
Thank you for useful library.

I have 2.13inch e-Paper HAT (C).
https://www.waveshare.com/wiki/2.13inch_e-Paper_HAT_(C)

This model have Black White & Yellow.
I tried epd2in13b-demo, but i can't see Yellow.

Do you have any solutions?

**Comment by nopnop2002** [comment]
It was my mistake.
I'm sorry.

Please close this issue.

**Comment by Bodmer** [comment]
OK, thanks for letting me know.
