### ISSUE TITLE
No ESP8266 overlap support after update to current library?

### ISSUE THREAD

**Issue by JamesNewton** [Bodmer/EPD_Libraries#3]
Unmodified Setup17_ePaper.h included from User_Setup_Select.h

epdif.h
````
#define RST_PIN         -1 // Connect EPD RST pin to ESP6266 RST
#define DC_PIN          14 //GPIO 14 NodeMCU D5. GPIO 2,  pin D4 will NOT work
#define CS_PIN          -1 // Defined in sketch in overlap mode as D3 (GPIO 0)
//#define BUSY_PIN         4 // Shared with DC, add 2K2 series resistor
#define BUSY_PIN       255 // No busy pin connected, use delays in sketch
````
Trying with 
\Arduino\libraries\epd1in54b\examples\epd1in54b-overlap\epd1in54b-overlap.ino

And the display just sits there. If I add some debug strings, it appears that the program never returns from the .Init() method. e.g. with this code:

````
  Serial.begin(9600);
  Serial.println("Start");
  delay(500);
  Epd epd;
  if (epd.Init() != 0) {
    Serial.print("e-Paper init failed");
    return;
  }
  Serial.println("Init");
  delay(500);
  epd.DisplayFrame(IMAGE_BLACK, IMAGE_RED);
  Serial.println("Done");
  delay(500);
````

I see "Start" but never "Init" or "Done"

**Comment by Bodmer** [comment]
Have you tried the same code on a bare ESP8266 board with nothing at all connected?

The overlap example is output only so has no need for a display to be connected to run.  If the code runs on a bare board then the hang may be due to something else that is connected to the board.

**Comment by Bodmer** [comment]
Not sure what happened but the Github version did not include overlap support.

Try the latest and edit as you have done.

**Comment by JamesNewton** [comment]
Thanks. It's working again.
