### ISSUE TITLE
SetPartialWindow unnecessarily restricting to positions 0-255

### ISSUE THREAD

**Issue by NeilMartin** [Bodmer/EPD_Libraries#4]
In file https://github.com/Bodmer/EPD_Libraries/blob/master/epd4in2/epd4in2.cpp

The function SetPartialWindow clips the x and y positions to one byte, which is max 255, like so...

SendData(x & 0xf8);     // x should be the multiple of 8, the last 3 bit will always be ignored
SendData(((x & 0xf8) + w  - 1) >> 8);
SendData(((x & 0xf8) + w  - 1) | 0x07);
SendData(y >> 8);        
SendData(y & 0xff);

As the display is 400x300, this needs to be larger. I've changed my version to the following so I can update the entire screen.

SendData(x & 0xfff8);     // x should be the multiple of 8, the last 3 bit will always be ignored
SendData(((x & 0xfff8) + w  - 1) >> 8);
SendData(((x & 0xfff8) + w  - 1) | 0x07);
SendData(y >> 8);        
SendData(y & 0xffff);

I discovered this when I was trying to paint a 96x150 block at 288,0

**Comment by Bodmer** [comment]
Missed this one! Now fixed.
Thanks.
